# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cheep < Formula
  desc "The most results per dollar: a smart orchestrator coordinates cheap/local executor agents."
  homepage "https://tedhaley.ca/cheep/"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TedHaley/cheep/releases/download/v0.5.0/cheep_darwin_amd64.tar.gz"
      sha256 "5afbb4b9c250873da4519046d62c53bbe4023c33b1e55b5d62534b1d453d7d07"

      define_method(:install) do
        bin.install "cheep"
        bin.install "cheep-claude-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TedHaley/cheep/releases/download/v0.5.0/cheep_darwin_arm64.tar.gz"
      sha256 "4a66c1f1f239be137f28b1d7e8b73dae10fbf3d53c67ba68f98811b0738a51df"

      define_method(:install) do
        bin.install "cheep"
        bin.install "cheep-claude-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TedHaley/cheep/releases/download/v0.5.0/cheep_linux_amd64.tar.gz"
      sha256 "8fd19a35371b8c42690c804a19c35fa0a358ad5a506fedfe0617d95ef1cb5fef"
      define_method(:install) do
        bin.install "cheep"
        bin.install "cheep-claude-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TedHaley/cheep/releases/download/v0.5.0/cheep_linux_arm64.tar.gz"
      sha256 "d662ad9eed47e42292d744d5ed7ac4c32447e25335ad4c65e49159877111fc6f"
      define_method(:install) do
        bin.install "cheep"
        bin.install "cheep-claude-mcp"
      end
    end
  end

  test do
    system "#{bin}/cheep", "version"
  end
end
