# This file was generated by GoReleaser. DO NOT EDIT.
cask "cheep" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "0cc09e5021a4af23a30f8ef4e07194f3de2c27a1ca413764f5e4b0a0a71171cb"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7598e17e519bbe09aa9a04ba3486b5643343c0ee0646e3795b1de0033a2846f3"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4096f996af64cc17f0608e96883214d686d16fb0df7b8ea1e3a49298ba527dee"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "197ed77f694692ecd06be2f4d2b59906fe5f77d1d99309dfe0db9a5c48f0d359"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_linux_arm64.tar.gz"
    end
  end

  name "cheep"
  desc "A Claude orchestrator that coordinates local Qwen executor agents."
  homepage "https://tedhaley.ca/cheep/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cheep"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cheep"]
    end
  end

  # No zap stanza required

end
