# This file was generated by GoReleaser. DO NOT EDIT.
cask "cheep" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "c66b202b6fc94b953a2199c33861efdd91dfcd0823ca6114399d28e297387608"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "724a56cb2edd081bed8065ce2ec7e79fcf01f1add87e640410e543a143706412"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bff856f0076d657deef40e9b53722d1e67cd542c5ef43f8dc291b0ff5085b691"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56aabe9c6ad70b2c15d049ab5fc833ca265f3e290f2d5a7ddddd7860f57bb7e9"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_linux_arm64.tar.gz"
    end
  end

  name "cheep"
  desc "A Claude orchestrator that coordinates local Qwen executor agents."
  homepage "https://tedhaley.ca/cheep/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cheep"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cheep"]
    end
  end

  # No zap stanza required

end
