# This file was generated by GoReleaser. DO NOT EDIT.
cask "cheep" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "9f959eb16c8ffbe5e56e27029aa6f523f8cb8a98d03bb5f4bdd7a7373ffe1be1"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7fca32e87bd9b56cbef02c304e0d94bf55fa1c42a162a92cf71b8f8ec147a89"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e61c470e3ac3c6d97d190e3ef9ca955af544526c1b6ee8bb58493ace27b58434"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfdbddfacd6ac80c4e5ece16a52fe2a516cac6fec71d209f74c642586307f08b"
      url "https://github.com/TedHaley/cheep/releases/download/v#{version}/cheep_linux_arm64.tar.gz"
    end
  end

  name "cheep"
  desc "A Claude orchestrator that coordinates local Qwen executor agents."
  homepage "https://tedhaley.ca/cheep/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cheep"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cheep"]
    end
  end

  # No zap stanza required

end
